name: fas_bloc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cloud_firestore: ^0.17.0-1.0.nullsafety.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^0.21.0-1.1.nullsafety.1
  firebase_messaging: ^9.0.0-1.0.nullsafety.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0-nullsafety.2
  freezed_annotation: ^0.13.0-nullsafety.0
  google_sign_in: ^5.0.0-nullsafety
  image_picker: ^0.7.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  freezed: ^0.13.0-nullsafety.2
  json_serializable: ^4.0.1
  mews_pedantic: ^0.1.3

flutter:
  uses-material-design: true
